### ISSUE TITLE
For Teachers

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#14]
**This will replace the current For Teachers page**
https://geology.utah.gov/teachers/

Preview Link: https://geology.utah.gov/?page_id=52137&preview=1&_ppp=1533d322d2

**Comment by Mackenzie-Cope** [comment]
I don't love the buttons to the popular geology topics. Maybe we can use some similar to the homepage buttons/images with icons and a fun font? Or just style them differently? Maybe with photos with buttons?

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Good work, looks great. A few suggestions:

- [ ] Teaching Kits rollover text: Format names of each teaching kit with a bullet (new line for each), instead of semicolons between each.
- [ ] Same suggestion for list items in the Earth Science Week and Multimedia & Downloads rollover text.
- [ ] The Thanksgiving Point link is dead now
- [ ] Is the rockhoundersock@yahoo.com email correct? (Looks like a typo but hard to tell...I would think it's rockhoundersrock@yahoo.com

**Comment by Mackenzie-Cope** [comment]
1. and 2. Bullets don't format well in those flip boxes, unfortunately. They get a little broken. I'll look into another option but for now I'll keep them in paragraphs. Thanks for the suggestion.
3. fixed the link
4. that is the correct email for them. the "ock" stands for outreach for community knowledge. I thought it was weird too but that's the email on their facebook page as well.

**Comment by Mackenzie-Cope** [comment]
Mike Hylland's Comments: 

- Under "For Teachers" text, middle-left photo: Maybe add "at Earth Science Week" (Dinosaurs and fossils at Earth Science Week)?
- Teacher Resources, Teaching Kits pop-up text: Consider deleting the first sentence (Call to reserve a teaching kit today). Seems like this prompt should be left to the actual Teaching Kits page.

**Comment by Mackenzie-Cope** [comment]
**1. Added "at Earth Science Week"
2. deleted first sentence**
