### ISSUE TITLE
Great Salt Lake & Lake Bonneville

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#16]
**This will replace the Lake Bonneville, Great Salt Lake, Bear Lake page**
https://geology.utah.gov/popular/general-geology/great-salt-lake/

Preview Link: https://geology.utah.gov/?page_id=50651&preview=1&_ppp=acfc147de2

**Comment by Mackenzie-Cope** [comment]
This may need some technical publications added.

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

DONE technical pubs added.

**Comment by marshallrobinson** [comment]
Looks great overall. A couple suggestions (let's chat about them when you have time):

- [ ] Technical publications are designed differently on the Dinos & Fossils webpage (I think I like how the GSL page does it instead - but I'm curious if it's possible to remove the redundant titles in the tab-content area?)
- [ ] Something seems off with the page title being Great Salt Lake while also having information about Lake Bonneville (Is it possible to split this into two pages without causing too much collateral consequences?)

**Comment by Mackenzie-Cope** [comment]
1. changed the dinos and fossils technical pubs to match GSL. I agree, it looks a little nicer. Also removed the redundant titles on the tabs.
2. Combined the GSL and LB content a bit more. Renamed the page Great Salt Lake and Lake Bonneville.
@marshallrobinson Mind taking another look to see if that solved the issue for you? And if there's any new comments from the slight design change? https://geology.utah.gov/?page_id=50651&preview=1&_ppp=6df2c6d7a8

**Comment by marshallrobinson** [comment]
Looks great!

**Comment by mikehylland** [comment]
- Intro text, first paragraph: There are several statements in this paragraph that either need clarification, or correction of the info presented.
     + This intro assumes the reader is already familiar with Lake Bonneville being a prehistoric lake, and many readers may not know that. Recommend this first mention of Lake Bonneville be something like "ancient Lake Bonneville," or "Ice Age Lake Bonneville," or "Pleistocene-age Lake Bonneville."
     + "...occupies the lowest depression in the Great Basin." Not true; the depression containing Death Valley is in the Great Basin, and is way lower than the Bonneville basin part of the Great Basin. And I suspect there are others.
     + "...has accommodated deposition of as much as 12,000 feet of sediment carried into the lake..." Unclear whether "the lake" is referring to Great Salt Lake or Lake Bonneville, but either way the statement would not be true. In the very deepest parts of the basin there might be as much as 12,000 feet of sediment, but that's the entire thickness of Holocene (i.e., Great Salt Lake), Pleistocene (i.e., Lake Bonneville, plus numerous other lakes, plus alluvial fill), Pliocene, and even Miocene basin-fill sediments.
- Intro text, 2nd paragraph: The last two sentences seem at odds with each other. One says "a small amount of dissolved salts...is deposited in GSL every year," but the next sentence says "about 2 million tons of dissolved salts enter the lake each year." Is 2 million tons really a "small" amount? If so, maybe some comparative example would be helpful to help the reader understand the relative amount of 2 million tons.
- Far left photo, pop-up caption: Perhaps "extension" is a better word than "stretching"? "Stretching" more technically applies to plastic/ductile deformation rather than brittle deformation (i.e., faulting).
- "Lake Bonneville Information," 1st sentence: The timeframe of Lake Bonneville is currently given as 30,000 to 13,000 years ago. Also, recommend using these 5-digit numbers rather than writing out "thousand," which is unconventional (by comparison, you later use "20,000 square miles" and "16,000 years ago").
- "Lake Bonneville Information," 2nd sentence: This statement about the "lowest closed depression in the EASTERN Great Basin" may be correct, but please confirm. Also, delete comma after "lowest."
- Image of Lake Bonneville and Great Salt Lake: Why is the Tooele 30x60 highlighted?
- Jim Davis has just completed an updated version of PI-39, Commonly Asked Questions about GSL and Ancient LB. He'd be a really good person to review this content to make sure it's technically solid.

**Comment by Mackenzie-Cope** [comment]
**1. added ancient
2. changed "the lowest" to "a" 
3. removed accommodation sentence (can't remember where this text came from to confirm)
4. took out the "small" wording to be more concise
5. changed wording to extension
6. fixed numbers
7. removed "lowest" wording
8. replaced LB image**

I will send to Jim to take a look. Good suggestion.

**Comment by Mackenzie-Cope** [comment]
I got some comments on the text from Jim. I have addressed all of his changes. See attached doc for edits.

[Great Salt Lake and Lake Bonneville Popular Geology jmd edits (1).docx](https://github.com/UGS-GIO/Website/files/9284666/Great.Salt.Lake.and.Lake.Bonneville.Popular.Geology.jmd.edits.1.docx)
