### ISSUE TITLE
Crude Oil

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#73]
Preview Link: https://geology.utah.gov/?page_id=49159

Replaces this page: https://geology.utah.gov/resources/energy/oil-gas/

**Comment by jackie-dewolfe** [comment]
**Addressed**- Intro paragraph refers to Utah’s ranking in 2018. Should that be updated to a more recent ranking (e.g., 2020?). Or, do we really want to tie the ranking to a specific year that requires updating from time to time? Alternatively, we could say something like “Utah has historically ranked in the top XX largest producers…”

Stiil needs addressing- Intro paragraph mentions central UT thrust belt fields, but no mention of the northern thrust belt fields. Seems like we should say something.

**Addressed**- Can we give general location of where the crude oil seep flowing over salt photo was taken?

**Addressed**- Petroleum Research Projects/Reservoir Studies section: Change “principle” to “principal.” At the end of that sentence, delete the hyphen between “petroleum” and “research” (petroleum research projects). 

Still needs addressing - In the list of projects, many of the linked pages still list Tom Chidsey as the point of contact; these will need to be updated.

**Addressed**- Utah’s Oil Booms: Rather than say “four oil booms in the past 65 years,” consider something like “four oil booms since large-scale production began in the 1940s.” That way the number of years doesn’t need to be updated from time to time.

**Addressed** (had to be changed from Utah Core Research Center to UCRC as it kicked "Center" onto a second line and it looked strange with button imbalances.)- In the Core Center News box, recommend referring to the Core Center as the Utah Core Research Center rather than the UGS Core Center.

**Comment by Mackenzie-Cope** [comment]
I'll send MVB an email asking for a sentence about the northern thrust belts. This may have to be added after we're live.

I put it on my to do list for after we're live to go through all the project pages and update contact info

**Comment by Mackenzie-Cope** [comment]
MVB didn't want to add anything about the northern thrust belts.
